gitlab:
  url: https://gitlab.si.c-s.fr

jupyterlab:
  url: https://nb.p2.csgroup.space

wizard:
  url: https://sharinghub.p2.csgroup.space/wizard

mlflow:
  type: mlflow-sharinghub
  url: https://sharinghub.p2.csgroup.space/mlflow

docs:
  url: https://sharinghub.p2.csgroup.space/docs

spaces:
  streamlit:
    url: https://kdeployer.p3.csgroup.space/deploy/
    assets:
      - streamlit_app.py

stac:
  extensions:
    eo: https://stac-extensions.github.io/eo/v1.1.0/schema.json
    label: https://stac-extensions.github.io/label/v1.0.1/schema.json
    sci: https://stac-extensions.github.io/scientific/v1.0.0/schema.json
    ml-model: https://stac-extensions.github.io/ml-model/v1.0.0/schema.json
  root:
    id: gitlab-cs
    title: SharingHub brings your data and models closer.
    description: Your platform for collaborating on ML and NLP projects store in [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.
    locales:
      fr:
        title: SharingHub rapproche vos données et vos modèles.
        description: Votre plateforme de collaboration sur les projets ML et NLP stockés dans le catalogue STAC de l'instance [GitLab](https://gitlab.si.c-s.fr).
  categories:
    - ai-model:
        title: "AI Models"
        description: "AI models are the core of our platform, go and browse them to discover our models."
        gitlab_topic: sharinghub:aimodel
        logo: https://data.web.p2.csgroup.space/sharinghub/ai-model.jpg
        icon: https://img.icons8.com/material/24/artificial-intelligence.png
        locales:
          fr:
            title: "Modèles IA"
            description: "Les modèles d'IA sont au cœur de notre plateforme, allez les parcourir pour découvrir nos modèles."
        features:
          deployment-spaces: disable
          jupyter: enable
          map-viewer: enable
          store-s3: enable
          mlflow: enable
    - dataset:
        title: "Datasets"
        description: "Datasets are very important in the process of training an AI, discover those that we put at your disposal."
        gitlab_topic: sharinghub:dataset
        logo: https://data.web.p2.csgroup.space/sharinghub/datasets.jpg
        icon: https://img.icons8.com/ios/50/data-backup.png
        locales:
          fr:
            title: "Jeux de données"
            description: "Les jeux de données sont très importants dans le processus de formation d'une IA, découvrez ceux que nous mettons à votre disposition."
        features:
          deployment-spaces: disable
          jupyter: enable
          map-viewer: enable
          store-s3: enable
          mlflow: disable
    - processor:
        title: "Processors"
        description: "A list of useful tools for working with your models."
        gitlab_topic: sharinghub:processor
        logo: https://data.web.p2.csgroup.space/sharinghub/processor.jpg
        icon: https://img.icons8.com/pulsar-line/48/maintenance.png
        locales:
          fr:
            title: "Processeurs"
            description: "Une liste d'outils directement utiles pour travailler avec vos modèles."
        features:
          deployment-spaces: disable
          jupyter: disable
          map-viewer: disable
          store-s3: disable
          mlflow: disable
    - tools:
        title: "Tools/Libraries"
        description: "We list tools and libraries that can make your life easier in the development of your models, or their use."
        gitlab_topic: sharinghub:tools
        logo: https://data.web.p2.csgroup.space/sharinghub/tools.jpg
        icon: https://img.icons8.com/pulsar-line/48/full-tool-storage-box-.png
        locales:
          fr:
            title: Outils/Librairies
            description: Nous répertorions des outils et librairies pouvant vous faciliter la vie dans le développement de vos modèles, ou bien leur utilisation.
        features:
          deployment-spaces: disable
          jupyter: disable
          map-viewer: disable
          store-s3: disable
          mlflow: disable
    - dashboard:
        title: "Dashboards"
        description: "Try using models with dashboards, for a visual and intuitive demonstration!"
        gitlab_topic: sharinghub:space
        logo: https://data.web.p2.csgroup.space/sharinghub/space.jpg
        icon: https://img.icons8.com/pulsar-line/48/run-command.png
        assets:
          - glob: "streamlit_app.py"
            title: "Streamlit App"
        locales:
          fr:
            title: "Dashboards"
            description: "Essayez d'utiliser des modèles avec les dashboards, pour une demonstration visuelle et intuitive !"
        features:
          deployment-spaces: enable
          jupyter: enable
          map-viewer: disable
          store-s3: disable
          mlflow: disable

tags:
  gitlab:
    minimum_count: 1
  sections:
    - name: "Computer Vision"
      enabled_for:
        - ai-model
        - dataset
        - processor
        - tools
        - dashboard
      keywords:
        - "Image qualification"
        - "Object detection"
        - "Image segmentation"
        - "Mask generation"
    - name: "Multimodal"
      keywords:
        - "Feature Extraction"
        - "Text-to-Image"
        - "Image-to-3D"
        - "Text-to-3D"
      enabled_for:
        - ai-model
        - dataset
        - processor
        - dashboard
    - name: "Tabular"
      keywords:
        - "Tabular Classification"
        - "Tabular Regression"
      enabled_for:
        - ai-model
        - dataset
        - processor
        - dashboard

alerts:
  timeout: 3
  type: info
  title: "Welcome to SharingHub"
  message: "To see all projects and unlock all features, please login..."
  locales:
    fr:
      title: "Bienvenue sur le SharingHub"
      message: "Pour voir tous les projets et débloquer toutes les fonctionnalités, veuillez vous connecter..."
