gitlab:
  url: https://gitlab.si.c-s.fr

jupyterlab:
  url: https://nb.p2.csgroup.space

stac:
  root:
    id: gitlab-cs
    title: GitLab CS STAC Catalog
    description: Custom description for this [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.
  catalogs:
    topics:
      ai-model:
        title: AI Models
        description: Custom AI models hosted on [GitLab](https://gitlab.si.c-s.fr)
        gitlab_name: sharinghub:aimodel
        locales:
          fr:
            title: Modèles IA
        features:
          deployment: enable
          map-viewer: enable
      dataset:
        title: Datasets
        gitlab_name: sharinghub:dataset
        locales:
          fr:
            title: Jeux de données
        features:
          deployment: enable
          map-viewer: enable
      processor:
        title: Tools and libraries
        gitlab_name: sharinghub:processor
        locales:
          fr:
            title: Outils et librairies
        features:
          deployment: disable
          map-viewer: disable
      challenge:
        title: Challenges
        gitlab_name: sharinghub:challenge
        locales:
          fr:
            title: Défis
        features:
          deployment: disable
          map-viewer: disable
