gitlab:
  url: https://gitlab.si.c-s.fr

jupyterlab:
  url: https://nb.p2.csgroup.space

mlflow:
  url: https://mlflow.p2.csgroup.space

docs:
  url: https://sharinghub.p2.csgroup.space/docs

spaces:
   streamlit:
     url: https://kdeployer.p3.csgroup.space/deploy/
     assets:
       - streamlit_app.py

stac:
  extensions:
    eo: https://stac-extensions.github.io/eo/v1.1.0/schema.json
    label: https://stac-extensions.github.io/label/v1.0.1/schema.json
    sci: https://stac-extensions.github.io/scientific/v1.0.0/schema.json
    ml-model: https://stac-extensions.github.io/ml-model/v1.0.0/schema.json
  root:
    id: gitlab-cs
    title: GitLab - CS Group
    description: Your platform for collaborating on ML and NLP projects stored in [GitLab](https://gitlab.si.c-s.fr).
    locales:
      fr:
        title: GitLab - CS Group
        description: Votre plateforme de collaboration sur les projets ML et NLP stockés dans [GitLab](https://gitlab.si.c-s.fr).
  categories:
    - ai-model:
        title: AI Models
        description: AI models are the core of our platform, go and browse them to discover our models.
        gitlab_topic: sharinghub:aimodel
        logo: https://data.web.p2.csgroup.space/sharinghub/ai-model.jpg
        icon: https://img.icons8.com/material/24/artificial-intelligence.png
        locales:
          fr:
            title: Modèles IA
            description: Les modèles d'IA sont au cœur de notre plateforme, allez les parcourir pour découvrir nos modèles.
        features:
          deployment-spaces: enable
          jupyter: disable
          map-viewer: enable
          store-s3: enable
          mlflow: enable
    - dataset:
        title: Datasets
        description: Datasets are very important in the process of training an AI, discover those that we put at your disposal.
        gitlab_topic: sharinghub:dataset
        logo: https://data.web.p2.csgroup.space/sharinghub/datasets.jpg
        icon: https://img.icons8.com/ios/50/data-backup.png
        locales:
          fr:
            title: Jeux de données
            description: Les jeux de données sont très importants dans le processus de formation d'une IA, découvrez ceux que nous mettons à votre disposition.
        features:
          deployment-spaces: disable
          jupyter: disable
          map-viewer: enable
          store-s3: enable
          mlflow: disable
    - processor:
        title: Tools and libraries
        description: We list tools and libraries that can make your life easier in the development of your models, or their use.
        gitlab_topic: sharinghub:processor
        logo: https://data.web.p2.csgroup.space/sharinghub/processor.jpg
        icon: https://img.icons8.com/pulsar-line/48/maintenance.png
        locales:
          fr:
            title: Outils et librairies
            description: Nous répertorions des outils et librairies pouvant vous faciliter la vie dans le développement de vos modèles, ou bien leur utilisation.
        features:
          deployment-spaces: disable
          jupyter: disable
          map-viewer: disable
          store-s3: disable
          mlflow: disable
    - challenge:
        title: Challenges
        description: Challenges may be offered to you here. Put yourself to the test!
        gitlab_topic: sharinghub:challenge
        logo: https://data.web.p2.csgroup.space/sharinghub/challenge.jpg
        icon: https://img.icons8.com/ios/50/mission-of-a-company.png
        assets:
          - glob: "streamlit_app.py"
            title: "Streamlit App"
        locales:
          fr:
            title: Défis
            description: Des défis pourront vous être proposés ici. Mettez-vous à l'épreuve!
        features:
          deployment-spaces: enable
          jupyter: enable
          map-viewer: enable
          store-s3: disable
          mlflow: disable

tags:
  gitlab:
    minimum_count: 1
  sections:
    - name: "Computer Vision"
      enabled_for:
        - ai-model
        - dataset
        - processor
        - challenge
      keywords:
        - "Image qualification"
        - "Object detection"
        - "Image segmentation"
        - "Mask generation"
    - name: "Multimodal"
      enabled_for:
        - ai-model
        - dataset
        - processor
      keywords:
        - "Feature Extraction"
        - "Text-to-Image"
        - "Image-to-3D"
        - "Text-to-3D"
    - name: "Tabular"
      enabled_for:
        - ai-model
        - dataset
        - processor
      keywords:
        - "Tabular Classification"
        - "Tabular Regression"

external-urls:
  - name: External Links
    icon: https://img.icons8.com/color/48/info--v1.png
    locales:
      fr:
        name: Liens Externes
    dropdown:
      - name: First Link
        url: https://icons8.com/icons/set/danger
        icon: https://img.icons8.com/ios/50/warning-shield.png
        locales:
          fr:
            name: Premier Lien
      - name: Second Link
        url: https://icons8.com/icons/set/stop
        icon: https://img.icons8.com/flat-round/64/stop.png
        locales:
          fr:
            name: Deuxième lien

alerts:
  timeout: 3
  type: info
  title: "Welcome to new SharingHub"
  message: "To see all projects and unlock all features, please login..."
  locales:
    fr:
      title: "Bienvenue sur le nouveau SharingHub"
      message: "Pour voir tous les projets et débloquer toutes les fonctionnalités, veuillez vous connecter..."
