remotes:
  gitlab.si.c-s.fr:
    title: GitLab CS STAC Catalog
    description: Custom description for this [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.

catalogs:
  topics:
    ai_model:
      title: AI Model
      description: Custom AI models hosted on [GitLab](https://gitlab.si.c-s.fr)
      default_type: item

    dataset:
      title: Dataset
      default_type: collection

    processor:
      title: Processor
