gitlab:
  url: https://gitlab.si.c-s.fr

jupyterlab:
  url: https://nb.p2.csgroup.space

stac:
  root:
    id: gitlab-cs
    title: GitLab - CS Group
    description: Your platform for collaborating on ML and NLP projects store in [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.
    locales:
      fr:
        title: GitLab - CS Group
        description: Votre plateforme de collaboration sur les projets ML et NLP stockés dans le catalogue STAC de l'instance [GitLab](https://gitlab.si.c-s.fr).
  catalogs:
    topics:
      ai-model:
        title: AI Models
        description: AI models are the core of our platform, go and browse them to discover our models.
        gitlab_name: sharinghub:aimodel
        logo: https://data.web.p2.csgroup.space/sharinghub/ai-model.jpg
        locales:
          fr:
            title: Modèles IA
            description: Les modèles d'IA sont au cœur de notre plateforme, allez les parcourir pour découvrir nos modèles.
        features:
          deployment: enable
          jupyter: disable
          map-viewer: enable
      dataset:
        title: Datasets
        description: Datasets are very important in the process of training an AI, discover those that we put at your disposal.
        gitlab_name: sharinghub:dataset
        logo: https://data.web.p2.csgroup.space/sharinghub/datasets.jpg
        locales:
          fr:
            title: Jeux de données
            description: Les jeux de données sont très importants dans le processus de formation d'une IA, découvrez ceux que nous mettons à votre disposition.
        features:
          deployment: disable
          jupyter: disable
          map-viewer: enable
      processor:
        title: Tools and libraries
        description: We list tools and libraries that can make your life easier in the development of your models, or their use.
        gitlab_name: sharinghub:processor
        logo: https://data.web.p2.csgroup.space/sharinghub/processor.jpg
        locales:
          fr:
            title: Outils et librairies
            description: Nous répertorions des outils et librairies pouvant vous faciliter la vie dans le développement de vos modèles, ou bien leur utilisation.
        features:
          deployment: disable
          jupyter: disable
          map-viewer: disable
      challenge:
        title: Challenges
        description: Challenges may be offered to you here. Put yourself to the test!
        gitlab_name: sharinghub:challenge
        logo: https://data.web.p2.csgroup.space/sharinghub/challenge.jpg
        locales:
          fr:
            title: Défis
            description: Des défis pourront vous être proposés ici. Mettez-vous à l'épreuve!
        features:
          deployment: disable
          jupyter: enable
          map-viewer: enable
