gitlab:
  url: https://gitlab.si.c-s.fr

stac:
  root:
    id: gitlab-cs
    title: GitLab CS STAC Catalog
    description: Custom description for this [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.
  catalogs:
    topics:
      ai-model:
        title: AI Models
        description: Custom AI models hosted on [GitLab](https://gitlab.si.c-s.fr)
        gitlab_name: sharinghub:aimodel
        locales:
          fr:
            title: Modèles IA
      dataset:
        title: Datasets
        gitlab_name: sharinghub:dataset
        locales:
          fr:
            title: Jeux de données
      processor:
        title: Tools and libraries
        gitlab_name: sharinghub:processor
        locales:
          fr:
            title: Outils et librairies
      challenge:
        title: Challenges
        gitlab_name: sharinghub:challenge
        locales:
          fr:
            title: Défis
