gitlab:
  url: https://gitlab.si.c-s.fr

stac:
  root:
    id: gitlab-cs
    title: GitLab CS STAC Catalog
    description: Custom description for this [GitLab](https://gitlab.si.c-s.fr) instance STAC catalog.
  catalogs:
    topics:
      ai-model:
        title: AI Model
        description: Custom AI models hosted on [GitLab](https://gitlab.si.c-s.fr)
        gitlab_name: sharinghub:aimodel
      dataset:
        title: Dataset
        gitlab_name: sharinghub:dataset
      processor:
        title: Processor
        gitlab_name: sharinghub:processor
      challenge:
        title: Challenge
        gitlab_name: sharinghub:challenge
