image:
  repository: 643vlk6z.gra7.container-registry.ovh.net/space_applications/gitlab2stac
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  -  name: regcred

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: gistac.p2.csgroup.space
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gistac-tls
      hosts:
        - gistac.p2.csgroup.space
