# Project information
site_name: "SharingHub Docs"
site_description: "Documentation of the SharingHub."
copyright: "Copyright &copy; 2024, CS Group"

# Configuration
site_dir: "build/html"
docs_dir: "src"
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  logo: assets/img/logo-white.png
  favicon: assets/img/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ["..", "src"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - macros:
      render_by_default: false
  - search:
      lang: en
  - tags
  - termynal

# Page tree
nav:
  - index.md
  - Tutorials:
      - tutorials/manage_dataset_with_dvc.md
      - tutorials/manage_dataset_with_shell.md
  - Legal Notice:
      - legal/terms-of-service.md
      - legal/privacy.md
      - legal/about-us.md

# Footer links
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: "https://gitlab.si.c-s.fr/space_applications/mlops-services/sharinghub-docs"
    - icon: fontawesome/solid/copyright
      link: "https://www.csgroup.eu"
